language: python

# Needed for Python 3.7
dist: bionic

python:
    - 3.6.11
    - 3.7.8
    - 3.8.5
# moto is incompatible with 3.5 because it relies on the key order of its url path regex rules
#    - 3.5.9

install:
    ## Install project dependencies into cached venv
    ## https://docs.gitlab.com/ee/ci/caching/#caching-python-dependencies
    - python -V
    - pip install -U pip setuptools virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
    - source $HOME/.poetry/env
    - poetry run python -m pip install -r requirements.dev
    - poetry install -v --no-interaction --extras all
    - poetry show -t --no-dev

script:
    - source $HOME/.poetry/env
    - make mototest
after_success:
    codecov
deploy:
    provider: pypi
    distributions: "sdist bdist_wheel"
    user: aio-libs-bot
    password:
        secure: sO1h+qa0JL3G5sImVzDfsX6W1Ilgz+I+EFXSfJ+O3vzqa4/M8qjVFuNrJafq59AkCG0LVdOC5gx1WSnsKmG+/Y92nQxzS43MhirgVEYKiBHQCNzlaH+Tha+JxP+reuDk6kB1oINnjuEldSfTMmNxYb+qL52Xvvjgk+Ho0XKzzMc/gBOshMNAZEPS9PUXg/CAyGYYsD/1VBjxCak4b9m8eegY0uRdKq9Cm2wUF2E9rWnYMlWRy0+wZHVaVysDeENF53rHtEVkQG9iuXM+uWhRu/288MpoVSKYzAcpQ16tr627NeW4VjWlC4LjLISRBC8sguapN1X7C6VIn/skoATe9yalxTuDmtqVgiYNW5kQWU07+g30+uvdWOCko7oJ4UoVoeHbnXe32z8rHAckXWu2hordC4exwTfAwd5iUSiAR95GfzFpbx0sCM8ahiEk62XzaiSP1RtSsGjtVxBjOA03EqzLCMGULbk5r7imFXw6+YaV5AYerk6fV0UNpMc5t8gfFFu6IxMc05eEMHypIEGgsKfp412+g5I33AjcpW4uyYf37RPPG/vMq4qlf9aVI8lNCFuDNqcnjeY3LxU/wbpOSmI0chdzSHS11M7F1NgeaVTGcQx4GvqBslSqRmNv0q1bdteMC2rVNkU0BGaBHKMIs97tUr2B6uFiswNdEsGorhY=
    on:
        tags: true
        repo: aio-libs/aiobotocore
        all_branches: true
        python: 3.7
        skip_existing: true

cache: pip

# tags are considered branches, so we need a regex to allow for them
# https://docs.travis-ci.com/user/customizing-the-build#safelisting-or-blocklisting-branches
branches:
  only:
  - master
  - /^\d+\.\d+\.\d+$/
